    /**
     * @dataProvider argumentsProvider
     * @test
     */

    public function it_throws_exception_when_second_parameter_is_lower_than_1($numberOfPieces, $mustThrow)
    {
        $exception = null;

        try {
            array_split([], $numberOfPieces);
        } catch (\InvalidArgumentException $exception) {
        }

        $this->assertSame($mustThrow, $exception instanceof \InvalidArgumentException);
    }
