    /**
     * @exepctedExceptionMessage Cannot resolve a fulfilled promise
     */

    public function testCannotResolve()
    {
        $this->expectException(\LogicException::class);

        $p = new FulfilledPromise('foo');
        $p->resolve('bar');
    }
